In [ ]:
import pandas as pd
from scipy import stats

In [117]:
test1_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/shap/2D/2D_Train_Test_1/Test1_shap_values.csv')
test2_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/shap/2D/2D_Train_Test_2/Test2_shap_values.csv')
test3_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/shap/2D/2D_Train_Test_3/Test3_shap_values.csv')
test4_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/shap/2D/2D_Train_Test_4/Test4_shap_values.csv')

In [ ]:
# test3_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/shap/2D/2D_Train_Test_3/Test3_test_data.csv')
test3_data = test3_data.drop(columns=['True_Label'])
feature_cols = [col for col in test3_data.columns if col not in ['Case_Name', 'Fold']]
test3_data[feature_cols] = test3_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test3_data_1 = test3_data[test3_data['Fold'] == 1]
test3_data_2 = test3_data[test3_data['Fold'] == 2]
test3_data_3 = test3_data[test3_data['Fold'] == 3]
test3_data_4 = test3_data[test3_data['Fold'] == 4]
test3_data_5 = test3_data[test3_data['Fold'] == 5]
# fold level average
test3_data_folds = pd.concat([test3_data_1, test3_data_2, test3_data_3, test3_data_4, test3_data_5])
test3_data_avg = test3_data_folds.groupby('Case_Name').mean().reset_index()
test3_data_avg = test3_data_avg.drop(columns=['Fold'])
test3_data_avg['total-shap'] = test3_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test3_data_avg = test3_data_avg[['Case_Name', 'total-shap']]

In [119]:
test2_data = test2_data.drop(columns=['True_Label'])
feature_cols = [col for col in test2_data.columns if col not in ['Case_Name', 'Fold']]
test2_data[feature_cols] = test2_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test2_data_1 = test2_data[test2_data['Fold'] == 1]
test2_data_2 = test2_data[test2_data['Fold'] == 2]
test2_data_3 = test2_data[test2_data['Fold'] == 3]
test2_data_4 = test2_data[test2_data['Fold'] == 4]
test2_data_5 = test2_data[test2_data['Fold'] == 5]
# fold level average
test2_data_folds = pd.concat([test2_data_1, test2_data_2, test2_data_3, test2_data_4, test2_data_5])
test2_data_avg = test2_data_folds.groupby('Case_Name').mean().reset_index()
test2_data_avg = test2_data_avg.drop(columns=['Fold'])
test2_data_avg['total-shap'] = test2_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test2_data_avg = test2_data_avg[['Case_Name', 'total-shap']]

In [120]:
test1_data = test1_data.drop(columns=['True_Label'])
feature_cols = [col for col in test1_data.columns if col not in ['Case_Name', 'Fold']]
test1_data[feature_cols] = test1_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test1_data_1 = test1_data[test1_data['Fold'] == 1]
test1_data_2 = test1_data[test1_data['Fold'] == 2]
test1_data_3 = test1_data[test1_data['Fold'] == 3]
test1_data_4 = test1_data[test1_data['Fold'] == 4]
test1_data_5 = test1_data[test1_data['Fold'] == 5]
# fold level average
test1_data_folds = pd.concat([test1_data_1, test1_data_2, test1_data_3, test1_data_4, test1_data_5])
test1_data_avg = test1_data_folds.groupby('Case_Name').mean().reset_index()
test1_data_avg = test1_data_avg.drop(columns=['Fold'])
test1_data_avg['total-shap'] = test1_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test1_data_avg = test1_data_avg[['Case_Name', 'total-shap']]

In [121]:
test4_data = test4_data.drop(columns=['True_Label'])
feature_cols = [col for col in test4_data.columns if col not in ['Case_Name', 'Fold']]
test4_data[feature_cols] = test4_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test4_data_1 = test4_data[test4_data['Fold'] == 1]
test4_data_2 = test4_data[test4_data['Fold'] == 2]
test4_data_3 = test4_data[test4_data['Fold'] == 3]
test4_data_4 = test4_data[test4_data['Fold'] == 4]
test4_data_5 = test4_data[test4_data['Fold'] == 5]
# fold level average
test4_data_folds = pd.concat([test4_data_1, test4_data_2, test4_data_3, test4_data_4, test4_data_5])
test4_data_avg = test4_data_folds.groupby('Case_Name').mean().reset_index()
test4_data_avg = test4_data_avg.drop(columns=['Fold'])
test4_data_avg['total-shap'] = test4_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test4_data_avg = test4_data_avg[['Case_Name', 'total-shap']]

In [122]:
# merge all shap values
total_shap_values = pd.concat([test1_data_avg, test2_data_avg, test3_data_avg, test4_data_avg])
total_shap_values

   Case_Name  total-shap
0     ahn_05    0.317479
1     ahn_09    0.457184
2     ahn_11    0.432930
3     ahn_12    0.394478
4     ahn_16    0.384185
..       ...         ...
66  nyu_0165    0.463950
67  nyu_0166    0.501703
68  nyu_0168    0.531197
69  nyu_0172    0.453426
70  nyu_0173    0.481815

[170 rows x 2 columns]

In [123]:
uncertainty_data = pd.read_excel('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/IPMN_all_cases_final.xlsx')
uncertainty_data = uncertainty_data[['ID', 'Total_uncertainty']]

uncertainty_data.rename(columns={'ID': 'Case_Name'}, inplace=True)
uncertainty_data
# merge uncertainty with shap values
total_shap_values_with_uncertainty = pd.merge(total_shap_values, uncertainty_data, on='Case_Name', how='left')

In [124]:
total_shap_values_with_uncertainty

    Case_Name  total-shap  Total_uncertainty
0      ahn_05    0.317479           0.850031
1      ahn_09    0.457184           0.629414
2      ahn_11    0.432930           0.656793
3      ahn_12    0.394478           0.472183
4      ahn_16    0.384185           0.566821
..        ...         ...                ...
165  nyu_0165    0.463950           0.562420
166  nyu_0166    0.501703           0.761913
167  nyu_0168    0.531197           0.719681
168  nyu_0172    0.453426           0.644419
169  nyu_0173    0.481815           0.746801

[170 rows x 3 columns]

In [ ]:
stats.ttest_rel(total_shap_values_with_uncertainty['total-shap'], total_shap_values_with_uncertainty['Total_uncertainty'])

TtestResult(statistic=-30.03013466787214, pvalue=1.1747357641519508e-69, df=169)

In [126]:
stats.mannwhitneyu(total_shap_values_with_uncertainty['total-shap'], total_shap_values_with_uncertainty['Total_uncertainty'])

MannwhitneyuResult(statistic=218.0, pvalue=1.4160275882253769e-55)

In [127]:
stats.pearsonr(total_shap_values_with_uncertainty['total-shap'], total_shap_values_with_uncertainty['Total_uncertainty'])

PearsonRResult(statistic=-0.3439491400092758, pvalue=4.3826188841662095e-06)

In [128]:
stats.spearmanr(total_shap_values_with_uncertainty['total-shap'], total_shap_values_with_uncertainty['Total_uncertainty'])

SignificanceResult(statistic=-0.38442974823065323, pvalue=2.2710984417865263e-07)