In [ ]:
import pandas as pd
from scipy import stats

In [ ]:
test1_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/lime/2D/2D_Train_Test_1/Test1_lime_values.csv')
test2_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/lime/2D/2D_Train_Test_2/Test2_lime_values.csv')
test3_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/lime/2D/2D_Train_Test_3/Test3_lime_values.csv')
test4_data = pd.read_csv('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/lime/2D/2D_Train_Test_4/Test4_lime_values.csv')

In [ ]:
test3_data = test3_data.drop(columns=['True_Label'])
feature_cols = [col for col in test3_data.columns if col not in ['Case_Name', 'Fold']]
test3_data[feature_cols] = test3_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test3_data_1 = test3_data[test3_data['Fold'] == 1]
test3_data_2 = test3_data[test3_data['Fold'] == 2]
test3_data_3 = test3_data[test3_data['Fold'] == 3]
test3_data_4 = test3_data[test3_data['Fold'] == 4]
test3_data_5 = test3_data[test3_data['Fold'] == 5]
# fold level average
test3_data_folds = pd.concat([test3_data_1, test3_data_2, test3_data_3, test3_data_4, test3_data_5])
test3_data_avg = test3_data_folds.groupby('Case_Name').mean().reset_index()
test3_data_avg = test3_data_avg.drop(columns=['Fold'])
test3_data_avg['total-lime'] = test3_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test3_data_avg = test3_data_avg[['Case_Name', 'total-lime']]

In [4]:
test2_data = test2_data.drop(columns=['True_Label'])
feature_cols = [col for col in test2_data.columns if col not in ['Case_Name', 'Fold']]
test2_data[feature_cols] = test2_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test2_data_1 = test2_data[test2_data['Fold'] == 1]
test2_data_2 = test2_data[test2_data['Fold'] == 2]
test2_data_3 = test2_data[test2_data['Fold'] == 3]
test2_data_4 = test2_data[test2_data['Fold'] == 4]
test2_data_5 = test2_data[test2_data['Fold'] == 5]
# fold level average
test2_data_folds = pd.concat([test2_data_1, test2_data_2, test2_data_3, test2_data_4, test2_data_5])
test2_data_avg = test2_data_folds.groupby('Case_Name').mean().reset_index()
test2_data_avg = test2_data_avg.drop(columns=['Fold'])
test2_data_avg['total-lime'] = test2_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test2_data_avg = test2_data_avg[['Case_Name', 'total-lime']]

In [5]:
test1_data = test1_data.drop(columns=['True_Label'])
feature_cols = [col for col in test1_data.columns if col not in ['Case_Name', 'Fold']]
test1_data[feature_cols] = test1_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test1_data_1 = test1_data[test1_data['Fold'] == 1]
test1_data_2 = test1_data[test1_data['Fold'] == 2]
test1_data_3 = test1_data[test1_data['Fold'] == 3]
test1_data_4 = test1_data[test1_data['Fold'] == 4]
test1_data_5 = test1_data[test1_data['Fold'] == 5]
# fold level average
test1_data_folds = pd.concat([test1_data_1, test1_data_2, test1_data_3, test1_data_4, test1_data_5])
test1_data_avg = test1_data_folds.groupby('Case_Name').mean().reset_index()
test1_data_avg = test1_data_avg.drop(columns=['Fold'])
test1_data_avg['total-lime'] = test1_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test1_data_avg = test1_data_avg[['Case_Name', 'total-lime']]

In [6]:
test4_data = test4_data.drop(columns=['True_Label'])
feature_cols = [col for col in test4_data.columns if col not in ['Case_Name', 'Fold']]
test4_data[feature_cols] = test4_data[feature_cols].abs()
# select from fold1 to fold5, if Fold = 1 , select this line
test4_data_1 = test4_data[test4_data['Fold'] == 1]
test4_data_2 = test4_data[test4_data['Fold'] == 2]
test4_data_3 = test4_data[test4_data['Fold'] == 3]
test4_data_4 = test4_data[test4_data['Fold'] == 4]
test4_data_5 = test4_data[test4_data['Fold'] == 5]
# fold level average
test4_data_folds = pd.concat([test4_data_1, test4_data_2, test4_data_3, test4_data_4, test4_data_5])
test4_data_avg = test4_data_folds.groupby('Case_Name').mean().reset_index()
test4_data_avg = test4_data_avg.drop(columns=['Fold'])
test4_data_avg['total-lime'] = test4_data_avg.drop(columns=['Case_Name']).sum(axis=1)
test4_data_avg = test4_data_avg[['Case_Name', 'total-lime']]

In [7]:
# merge all lime values
total_lime_values = pd.concat([test1_data_avg, test2_data_avg, test3_data_avg, test4_data_avg])
total_lime_values

   Case_Name  total-lime
0     ahn_05    0.257339
1     ahn_09    0.240657
2     ahn_11    0.251694
3     ahn_12    0.263385
4     ahn_16    0.270443
..       ...         ...
66  nyu_0165    0.237625
67  nyu_0166    0.224154
68  nyu_0168    0.233149
69  nyu_0172    0.227876
70  nyu_0173    0.240829

[170 rows x 2 columns]

In [8]:
uncertainty_data = pd.read_excel('/home/pyq6817/IPMN-Radiomics-Plus-Deeplearning/radiomics/SHAP&LIME/IPMN_all_cases_final.xlsx')
uncertainty_data = uncertainty_data[['ID', 'Total_uncertainty']]

uncertainty_data.rename(columns={'ID': 'Case_Name'}, inplace=True)
uncertainty_data
# merge uncertainty with lime values
total_lime_values_with_uncertainty = pd.merge(total_lime_values, uncertainty_data, on='Case_Name', how='left')

In [9]:
total_lime_values_with_uncertainty

    Case_Name  total-lime  Total_uncertainty
0      ahn_05    0.257339           0.850031
1      ahn_09    0.240657           0.629414
2      ahn_11    0.251694           0.656793
3      ahn_12    0.263385           0.472183
4      ahn_16    0.270443           0.566821
..        ...         ...                ...
165  nyu_0165    0.237625           0.562420
166  nyu_0166    0.224154           0.761913
167  nyu_0168    0.233149           0.719681
168  nyu_0172    0.227876           0.644419
169  nyu_0173    0.240829           0.746801

[170 rows x 3 columns]

In [10]:
stats.ttest_rel(total_lime_values_with_uncertainty['total-lime'], total_lime_values_with_uncertainty['Total_uncertainty'])

TtestResult(statistic=-64.48159026049608, pvalue=6.24586389559626e-121, df=169)

In [14]:
stats.mannwhitneyu(total_lime_values_with_uncertainty['total-lime'], total_lime_values_with_uncertainty['Total_uncertainty'])

MannwhitneyuResult(statistic=0.0, pvalue=3.0994744861912664e-57)

In [12]:
stats.pearsonr(total_lime_values_with_uncertainty['total-lime'], total_lime_values_with_uncertainty['Total_uncertainty'])

PearsonRResult(statistic=-0.007773495869717213, pvalue=0.9198618676720801)

In [13]:
stats.spearmanr(total_lime_values_with_uncertainty['total-lime'], total_lime_values_with_uncertainty['Total_uncertainty'])

SignificanceResult(statistic=0.01207247146756554, pvalue=0.8758358621364905)